project:
  type: website
  output-dir: docs
  render:
      - index.qmd

website:
  title: "FFP Overlay"
  navbar:
    left:
      - href: index.qmd
    right:
      - icon: github
        href: https://github.com/June-Skeeter/FFP_Overlay
        aria-label: Quarto GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



