---
title: "About FFP Overlay"
---

This Python application is a wrapper for the [Kljun et al. 2015](https://gmd.copernicus.org/articles/8/3695/2015/gmd-8-3695-2015.html) flux footprint prediction (FFP) model.  It allows users to incorporate spatial analysis in the FFP processing pipeline while speeding up FFP calculation parallelizing the processing. 

Kljun, N., Calanca, P., Rotach, M. W., & Schmid, H. P. (2015). A simple two-dimensional parameterisation for Flux Footprint Prediction (FFP). Geoscientific Model Development, 8(11), 3695–3713.

## Access

You may find the FFP Overlay repository [here](https://github.com/June-Skeeter/FFP_Overlay) along with documentation and instructions for installing the application.


## Example Output

Given half-hourly turbulence conditions and metadata for a site, this wrapper will calculate the FFP on a per-time-step basis, and output FFP contours over desired intervals in this web-map format.  If provided a landscape classification map, the program will also overlay each timestep's footprint with the map.  This allows the user to estimate the relative source contrition of different ecosystem components in some heterogeneous ecosystems.  @fig-output shows an example of the web map output for the Burns Bog 2 EC station.  @fig-classes gives an example of outputs that can be produced when a basemap ecosystem classification map is provided.

::: {#fig-output}

<div style="overflow: hidden;
  padding-top: 75%;
  position: relative">
  <iframe src="Example_Outputs/BB2_FFP_2m.html" title="Processes" scrolling="no" frameborder="0"
    style="border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;">
   <p>Your browser does not support iframes.</p>
 </iframe>
</div>

Flux footprint climatology (2021-2022) for the Burns Bog 2 Eddy Covariance Station, partitioned by season.

:::


::: {#fig-classes}

<div style="overflow: hidden;
  padding-top: 75%;
  position: relative">
  <iframe src="Example_Outputs/Summary_by_Basemap_Class.html" title="Processes" scrolling="no" frameborder="0"
    style="border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;">
   <p>Your browser does not support iframes.</p>
 </iframe>
</div>

Flux source area by ecosystem type (2021-2022) for the Burns Bog 2 Eddy Covariance Station, partitioned by season.

:::
